# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

satlins <- function(x) {
    .Call(`_elmNNRcpp_satlins`, x)
}

tribas <- function(x) {
    .Call(`_elmNNRcpp_tribas`, x)
}

hardlim <- function(x) {
    .Call(`_elmNNRcpp_hardlim`, x)
}

hardlims <- function(x) {
    .Call(`_elmNNRcpp_hardlims`, x)
}

relu <- function(x, alpha = 0.0) {
    .Call(`_elmNNRcpp_relu`, x, alpha)
}

set_seed <- function(seed) {
    invisible(.Call(`_elmNNRcpp_set_seed`, seed))
}

uniform_negative <- function(n_rows, n_cols) {
    .Call(`_elmNNRcpp_uniform_negative`, n_rows, n_cols)
}

activation_functions <- function(tempH, actfun, alpha = 0.0) {
    .Call(`_elmNNRcpp_activation_functions`, tempH, actfun, alpha)
}

elm_train_rcpp <- function(x, y, nhid, actfun, init_weights = "normal_gaussian", bias = FALSE, moorep_pseudoinv_tol = 0.01, alpha = 0.0, seed = 1L, verbose = FALSE) {
    .Call(`_elmNNRcpp_elm_train_rcpp`, x, y, nhid, actfun, init_weights, bias, moorep_pseudoinv_tol, alpha, seed, verbose)
}

norm_preds <- function(x) {
    .Call(`_elmNNRcpp_norm_preds`, x)
}

elm_predict_rcpp <- function(object, newdata, normalize = FALSE) {
    .Call(`_elmNNRcpp_elm_predict_rcpp`, object, newdata, normalize)
}

onehot_labels_rcpp <- function(x) {
    .Call(`_elmNNRcpp_onehot_labels_rcpp`, x)
}

